export const ADD_FOOD_TO_CART_REQUEST = "ADD_FOOD_TO_CART_REQUEST";
export const ADD_FOOD_TO_CART_SUCCESS = "ADD_FOOD_TO_CART_SUCCESS";
export const ADD_FOOD_TO_CART_FAILURE = "ADD_FOOD_TO_CART_FAILURE";

export const GET_CART_OF_USER_REQUEST = "GET_CART_OF_USER_REQUEST";
export const GET_CART_OF_USER_SUCCESS = "GET_CART_OF_USER_SUCCESS";
export const GET_CART_OF_USER_FAILURE = "GET_CART_OF_USER_FAILURE";

export const REMOVE_ITEM_FROM_CART_REQUEST = "REMOVE_ITEM_FROM_CART_REQUEST";
export const REMOVE_ITEM_FROM_CART_SUCCESS = "REMOVE_ITEM_FROM_CART_SUCCESS";
export const REMOVE_ITEM_FROM_CART_FAILURE = "REMOVE_ITEM_FROM_CART_FAILURE";