export const GET_SHOP_FOOD_REQUEST = "GET_SHOP_FOOD_REQUEST";
export const GET_SHOP_FOOD_SUCCESS = "GET_SHOP_FOOD_SUCCESS";
export const GET_SHOP_FOOD_FAILURE = "GET_SHOP_FOOD_FAILURE";

export const UPDATE_FOOD_STATUS_REQUEST = "UPDATE_FOOD_STATUS_REQUEST";
export const UPDATE_FOOD_STATUS_SUCCESS = "UPDATE_FOOD_STATUS_SUCCESS";
export const UPDATE_FOOD_STATUS_FAILURE = "UPDATE_FOOD_STATUS_FAILURE";