export const GET_ALL_FOOD_REQUEST = "GET_ALL_FOOD_REQUEST";
export const GET_ALL_FOOD_SUCCESS = "GET_ALL_FOOD_SUCCESS";
export const GET_ALL_FOOD_FAILURE = "GET_ALL_FOOD_FAILURE";

// Get food by shop
export const GET_SHOP_FOOD_REQUEST = "GET_SHOP_FOOD_REQUEST";
export const GET_SHOP_FOOD_SUCCESS = "GET_SHOP_FOOD_SUCCESS";
export const GET_SHOP_FOOD_FAILURE = "GET_SHOP_FOOD_FAILURE";