export const GET_SHOPS_REQUEST = 'GET_SHOPS_REQUEST';
export const GET_SHOPS_SUCCESS = 'GET_SHOPS_SUCCESS';
export const GET_SHOPS_FAILURE = 'GET_SHOPS_FAILURE';

export const GET_SHOP_DETAIL_REQUEST = 'GET_SHOP_DETAIL_REQUEST';
export const GET_SHOP_DETAIL_SUCCESS = 'GET_SHOP_DETAIL_SUCCESS';
export const GET_SHOP_DETAIL_FAILURE = 'GET_SHOP_DETAIL_FAILURE'; 