export const GET_ORDER_BY_SHOP_REQUEST = "GET_ORDER_BY_SHOP_REQUEST";
export const GET_ORDER_BY_SHOP_SUCCESS = "GET_ORDER_BY_SHOP_SUCCESS";
export const GET_ORDER_BY_SHOP_FAILURE = "GET_ORDER_BY_SHOP_FAILURE";

export const UPDATE_ORDER_STATUS_REQUEST = "UPDATE_ORDER_STATUS_REQUEST";
export const UPDATE_ORDER_STATUS_SUCCESS = "UPDATE_ORDER_STATUS_SUCCESS";
export const UPDATE_ORDER_STATUS_FAILURE = "UPDATE_ORDER_STATUS_FAILURE";