export const CREATE_SHOP_REQUEST = "CREATE_SHOP_REQUEST";
export const CREATE_SHOP_SUCCESS = "CREATE_SHOP_SUCCESS";
export const CREATE_SHOP_FAILURE = "CREATE_SHOP_FAILURE";

export const GET_SHOP_BY_ID_REQUEST = 'GET_SHOP_BY_ID_REQUEST';
export const GET_SHOP_BY_ID_SUCCESS = 'GET_SHOP_BY_ID_SUCCESS';
export const GET_SHOP_BY_ID_FAILURE = 'GET_SHOP_BY_ID_FAILURE';