export const CREATE_SHOP_REQUEST = "CREATE_SHOP_REQUEST";
export const CREATE_SHOP_SUCCESS = "CREATE_SHOP_SUCCESS";
export const CREATE_SHOP_FAILURE = "CREATE_SHOP_FAILURE";

export const GET_SHOP_BY_ID_REQUEST = 'GET_SHOP_BY_ID_REQUEST';
export const GET_SHOP_BY_ID_SUCCESS = 'GET_SHOP_BY_ID_SUCCESS';
export const GET_SHOP_BY_ID_FAILURE = 'GET_SHOP_BY_ID_FAILURE';

export const UPDATE_SHOP_REQUEST = "UPDATE_SHOP_REQUEST";
export const UPDATE_SHOP_SUCCESS = "UPDATE_SHOP_SUCCESS";
export const UPDATE_SHOP_FAILURE = "UPDATE_SHOP_FAILURE";

export const UPDATE_SHOP_STATEMENT_REQUEST = "UPDATE_SHOP_STATEMENT_REQUEST";
export const UPDATE_SHOP_STATEMENT_SUCCESS = "UPDATE_SHOP_STATEMENT_SUCCESS";
export const UPDATE_SHOP_STATEMENT_FAILURE = "UPDATE_SHOP_STATEMENT_FAILURE";